### ISSUE TITLE
Transition the compiler from GCC to Clang

### ISSUE THREAD

**Issue by alanjian85** [carg-os/carg-os#2]
Transitioning the compiler from GCC to Clang offers several advantages. These include smoother integration of the kernel with Rust userland and simplified compiler installation via package managers in major Linux distributions, rather than relying on a separate pre-compiled binary archive (such as [carg-os/riscv-gnu-toolchain](https://github.com/carg-os/riscv-gnu-toolchain)). It's important to note that any usage of GNU-specific features in the current implementation should be removed during this transition.

**Comment by Cycatz** [comment]
Do we have any GNU-specific features?

**Comment by alanjian85** [comment]
> Do we have any GNU-specific features?

Hardly any, though it may be tricky to port Newlib to Clang. You can try porting earlier versions first.

**Comment by Cycatz** [comment]
See branch https://github.com/carg-os/carg-os/tree/llvm

**Comment by alanjian85** [comment]
Thank @Cycatz for contributing!
